<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php
function getMagentoCategoriesAsFlattenArray () {
  $categories_collection = Mage::getModel('catalog/category')->getCollection();
  $categories_collection->addAttributeToSelect('name')->addAttributeToSelect('parent_id')->setStoreId( Mage::app()->getStore()->getId() )->load ();
  $result = array ();

  if($categories_collection->getSize()){
    foreach($categories_collection as $category) {
      $result [] = array (
        "id"  => $category->getId(),
        "parent_id" => $category->getParentId(),
        "level" => $category->getLevel(),
        "name" => $category->getName(),
        "url" => $category->getUrl()
      );
    }
  }
    return $result;
}
?>

<?php $_menu = $this->renderCategoriesMenuHtml( 0,'level-top') ?>
<?php if($_menu): ?>
<div class=" bs-docs-sidebar">
    <!--ul class="nav nav-list bs-docs-sidenav affix"-->
    <ul class="nav nav-list bs-docs-sidenav">
        <!--li class="nav-header"><?php echo $this->__('Browse By') ?></li-->
        <?php echo $_menu ?>
    </ul>
</div>
<?php endif ?>

<!--
  <?php /*
    $_ctg = getMagentoCategoriesAsFlattenArray ();
    foreach($_ctg as $_category) {
      echo $_category['id'] . " " . $_category['parent_id'] ."\n";
    }
    */
  ?>
-->
