<?php
/**
 * CorlleteLab
 *
 * Imagezoom extension
 *
 * @category   CorlleteLab
 * @package    CorlleteLab_Imagezoom
 * @copyright  Copyright (c) 2011 Corllete Ltd. (http://www.clabteam.com/)
 * @author     CorlleteLab Dev Team <office@clabteam.com>
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
	$zoom_image_size = Mage::getStoreConfig('imagezoomconfig/imagezoom_style_css/img_size');
	$images_to_show = Mage::getStoreConfig('imagezoomconfig/imagezoom_images/imagesToShow');
	$images_to_show = $images_to_show != '' ? $images_to_show : 999;
	$img_arr = array();
	
	if ($_product->getTypeId() == 'configurable') {
echo $this->__('<!--[');	
    $CAtrr = array();
    foreach( $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product) as $attr ) {
      $CAttr[ $attr['attribute_code'] ] = array();
      foreach ( $attr['values'] as $value ) {
        $CAttr[ $attr['attribute_code'] ][ $value['store_label']] = $value['value_index'];
      }
    }
		
		$_childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProductCollection($_product);

		if (count($_childProducts) > 0) {
			$cnt = 0;
			$js = '';
			foreach ($_childProducts as $_child) {
/*
        $_child_product = Mage::getModel('catalog/product')->load($_child->getId());
        $_image_classes = array();
        foreach( $CAttr as $name => $attr ) {
          $_image_classes[] = $name . "[" . $attr[ $_child_product->getAttributeText( $name ) ] . "]";
        }
        //echo join( " ", $_image_classes );
        //echo $this->__("\n");
*/
				$_child_images = $this->helper('imagezoom')->getAllImages($_child);
        $img_number = 0;
				foreach($_child_images as $_child_image) {
          if($img_number++ == 1 ) {
            $img_arr[$cnt] = array(
                      'id' => $_child->getId(),
                      'small_image' => (string)$this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_child_image->getFile())->resize($zoom_image_size),
                      'big_image' => (string)$this->helper('catalog/image')->init($this->getProduct(), 'image', $_child_image->getFile()),
                      'thumb' => (string)$this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_child_image->getFile())->resize(56),
                      'label' => (string)$this->htmlEscape($_child_image->getLabel()),
                      'main_image' => (string)$_child_image['main_image'],
                      'product_url' => (string)$_child->getProductUrl()
                    );
            //echo Mage::helper('core')->jsonEncode( $img_arr[$cnt] );
            $cnt++;
          }
				}
			}
		}
echo $this->__(']-->');	
		
	
	} else if($_product->getTypeId() == 'grouped') { //TODO
		//$_childProducts = $_product->getTypeInstance()->getAssociatedProducts();
	}	
?>

<?php if ($_product->getTypeId() == 'configurable' ):?>
<script type="text/javascript">
  jQuery(document).ready(function(){
     jQuery('#product-options-wrapper, div.product-options-bottom').hide();
  });
</script>
<?php endif;?>

<script type="text/javascript">
  var assocIMG = { // Added
  <?php
  	if(isset($img_arr) && count($img_arr) > 0) {
		$dados = array();
		foreach ($img_arr as $img) {
			if ($img['main_image']) {
				$dados[] = "small_image_".$img['id'].":'".$img['small_image']."'";
				$dados[] = "big_image_".$img['id'].":'".$img['big_image']."'";
			}
		}
	  	echo implode(',', $dados );   
	}
  ?>
  }   
</script>

<script type="text/javascript">
	function jSelectImage(id) {
		hideSelected(id);
		
		if (assocIMG['big_image_'+id] && assocIMG['small_image_'+id]) {
			// Destroy the previous zoom
			jQuery('#image-zoom').data('zoom').destroy();
			// Change the biglink to point to the new big image.
			jQuery('#image-zoom').attr('href', assocIMG['big_image_'+id]);
			// Change the small image to point to the new small image.
			jQuery('#image-zoom img').attr('src', assocIMG['small_image_'+id]);
			// Init a new zoom with the new images.				
			jQuery('#image-zoom').CloudZoom();
			//console.log('yes');
		}
	}
	
	function hideSelected(id) {
		//console.log(id);
		var add = $$('.more-views li.add');
		if (add && add.length > 0) {
			$('show-all').show();
			add.each(function(item,i){
				item.hide();
				var className = 'item-'+id;
				
				if (item.hasClassName(className)){
					item.show();
				}
			})
		}
	}
	
	function showAll() {
		var add = $$('.more-views li.add');
		if (add && add.length > 0) {
			$('show-all').hide();
			add.each(function(item,i){
				item.show();				
			})
		}	
	}
	
</script>

<p class="product-image">
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="image-zoom" rel="<?php echo $this->helper('imagezoom')->getZoomConfig(); ?>">
	<?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($zoom_image_size).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
	</a>
</p>


<?php if (count($this->getGalleryImages()) > 0 || (isset($_childProducts) && count($_childProducts) > 0) ): ?>
<div class="more-views">
	<a id="show-all" class="f-right" style="display: none; font-size: 11px" href="#" onclick="javascript:showAll(); return false;" title="Show All"><?php echo $this->__('Show All') ?></a>
    <?php if ($_product->getTypeId() == 'configurable' ):?>
      <h2><?php echo $this->__('Choose a product') ?></h2>
    <?php else:?>
      <h2><?php echo $this->__('More Views') ?></h2>    
    <?php endif;?>

    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" class="cloud-zoom-gallery" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"
				rel="useZoom: 'image-zoom', smallImage: '<?php  echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($zoom_image_size) ?>'" >
				<img src="<?php  echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56) ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
			</a>
        </li>
    <?php endforeach; ?>
	<?php if (isset($_childProducts) && count($_childProducts) > 0):?>
		<?php $cnt = 0; ?>
		<?php foreach ($img_arr as $img): ?>
        <li class="add item-<?php echo $img['id']; ?>"<?php if ($cnt >= $images_to_show) : ?> style="display: none"<?php endif; ?>>
            <a href="<?php if ($_product->getTypeId() == 'configurable') {echo $img['product_url'] . '"';} else {echo $img['big_image'] . '" class="cloud-zoom-gallery"'; } ?> title="<?php echo $img['label'] ?>"
				rel="useZoom: 'image-zoom', smallImage: '<?php  echo $img['small_image']; ?>'" >
				<img src="<?php  echo $img['thumb']; ?>" alt="<?php echo $img['label'] ?>" />
			</a>
        </li>	
		<?php $cnt++; ?>	
		<?php endforeach; ?>
		
		<li style="padding: 0; background-color: transparent; display: none"></li>
		<?php if ($cnt >= $images_to_show) : ?>
			<script type="text/javascript">
				$('show-all').show();
			</script>
		<?php endif; ?>
	<?php endif; ?>
    </ul>
	
</div>
<?php endif; ?>